# Generated by Django 5.2.6 on 2025-09-26 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_auditlog_details_alert_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='reagent',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='reagent',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='reagent',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produto')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stocklot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alert',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.produto'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.produto'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.produto'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklot',
            unique_together={('produto', 'lot_number')},
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='reagent',
        ),
        migrations.DeleteModel(
            name='Reagent',
        ),
    ]
